server:
    #PUERTO
    port: 9500
spring: 
    application:
        # NOMBRE DE LA APLICACIÓN
        name: compras-ventas2
    datasource:
        # CONFIGURACIÓN DE LA BASE DE DATOS POSTGRESQL
        driver-class-name: org.postgresql.Driver
        # URL DE CONEXIÓN A LA BASE DE DATOS
        url: jdbc:postgresql://localhost:5432/compras-ventas2
        # USUARIO Y CONTRASEÑA
        username: postgres
        password: admin
    jpa:
        # DDL-AUTO CONFIGURADO EN CREATE-DROP PARA CREAR Y 
        # ELIMINAR LAS TABLAS EN CADA EJECUCIÓN
        hibernate:
            ddl-auto: create-drop
        show-sql: true 
 #PARA UTILIZAR LOS LOGS       
logging:
    level:
        root: INFO
        com.blumbit.comprasVentas2: DEBUG
        org.springframework.web: WARN
        org.hibernate: WARN
    file:
        name: logs/comprasVentas2.log
    logback:
        rollingpolicy:
            file-name-pattern: logs/comprasVentas2-%d{yyyy-MM-dd}.%i.log
            max-history: 30
            max-file-size: 10MB
            total-size-cap: 1GB
#PARA REFRESH TOKEN
application:
    jwt:
        #clave secreta
        secret-key: mysecretkey
        #tiempo de expiracion  - 15 minutos por eso esta 9000 que es en milisegundos
        access-token-expiration: 9000
        refresh-token-expiration: 604800000 # 7 dias en milesegundos
            

          
            

#El Access Token es el token utilizado para acceder a los recursos protegidos de la API. 
#Tiene una duración corta por motivos de seguridad. Cuando expira, el usuario no necesariamente 
#debe volver a iniciar sesión porque existe el Refresh Token. El Refresh Token tiene una duración mayor 
#y permite solicitar nuevos Access Tokens sin volver a ingresar las credenciales. Solamente cuando el Refresh 
#Token expira, el usuario deberá autenticarse nuevamente.